Improve `rename_like`
xarray-contrib/cf-xarray pull request #222
Opened 2021-05-01 17:51 UTC by malmans2

`rename_like` also updates the `bounds` and `cell_measures` attributes.

2021-05-26 18:27 UTC, dcherian requested changes

2021-05-26 18:27 UTC, dcherian commented on cf_xarray/accessor.py
> +        def get_renamer_and_conflicts():
```suggestion
        def get_renamer_and_conflicts(keydict):
```

2021-05-26 18:27 UTC, dcherian commented on cf_xarray/accessor.py
> +        renamer, conflicts = get_renamer_and_conflicts()
```suggestion
        renamer, conflicts = get_renamer_and_conflicts(keydict)
```

2021-05-26 18:27 UTC, dcherian commented on cf_xarray/accessor.py
> +            renamer, conflicts = get_renamer_and_conflicts()
```suggestion
            renamer, conflicts = get_renamer_and_conflicts(keydict)
```

2021-05-27 12:29 UTC, dcherian approved these changes

2021-05-27 12:44 UTC, dcherian commented
Docs failure is related to this PR

2021-05-27 12:49 UTC, malmans2 commented
> Docs failure is related to this PR

I don't think so, main is failing as well. I'm not sure what change (I guess in `xarray`?) but this would fix it: https://github.com/xarray-contrib/cf-xarray/pull/227#discussion_r637399243

2021-05-27 13:59 UTC, merged